trigger:
  batch: true
  branches: 
    include :
     -main
  paths:
    include:
      - /hammad.yaml
pool:
  vmImage: ubuntu-latest
steps:
- script: echo "Salam From Syed Hammad Ahmed"
  displayName: "This is my frist auzur pipeline"