trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /parameters/main-stages.yaml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Stage_1
  jobs:
   - template: /parameters/template-job.yaml
     parameters: 
       stgname: stage_1 parameter
       env: dev

- stage: Stage_2
  jobs:
   - template: /parameters/template-job.yaml 
     parameters: 
       stgname: stage_2 parameter
       env: qa 
  
- stage: Stage_3
  jobs:
   - template: /parameters/template-job.yaml
     parameters: 
       env: uat