parameters:
- name: stgname
  default: stage_parameter
  type: string

- name: env
  default: ''
  type: string


jobs:
 - job: Job1
   displayName: Job
   continueOnError: true
   workspace:
    clean: outputs
   steps:
   - script: echo ${{ parameters.stgname }} 
     displayName: parameter_1
   - script: echo ${{ parameters.env }}
     displayName: parameter_2
        

