trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /heirarchy/stages.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Stage_1
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

- stage: Stage_2
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2
  
- stage: Stage_3
  jobs:
   - job: Job1
     displayName: First Job
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2