trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /variables/main-variable.yml

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob
    variables:
     - template: /variables/variable-template.yaml
    steps:
    - script: echo $(my_var) ${{ variables.var1 }} ${{ variables.var2 }} ${{ variables.var3 }}