trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /variables/variable-group-ex.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
   - group: pipeline-variable-group
  jobs:
  - job: FirstJob
    steps:
    - script: echo $(my_var)